# Generated by Django 5.0 on 2023-12-15 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_rename_category_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Paypal', 'Paypal'), ('Card', 'Card'), ('Bank', 'Bank')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Damaged', 'Damaged')], max_length=7),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.payment_method')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.buyer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer'),
        ),
        migrations.CreateModel(
            name='Order_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.order_date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.order_date'),
        ),
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.order_status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='seller.payment_method'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.payment_method'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.price'),
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.quantity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.quantity'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Processed', 'Processed'), ('Out for Delivery', 'Out for Delivery'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.AddField(
            model_name='order_status',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.status'),
        ),
    ]
