# Generated by Django 5.0 on 2023-12-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_payment_method_remove_message_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], max_length=20)),
                ('paymment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.payment_method')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.transaction_status'),
        ),
    ]
