# Generated by Django 5.0 on 2023-12-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_alter_seller_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Books', 'Books'), ('Phones and Tablets', 'Phones and Tablets'), ('Laptop', 'Laptop'), ('Camera', 'Camera'), ('Home Appliances', 'Home Appliances'), ('Clothing', 'Clothing')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
