# Generated by Django 5.0 on 2023-12-16 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_categorie_category_alter_seller_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='name',
        ),
    ]
