# Generated by Django 5.0 on 2023-12-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_remove_categorie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='product_name',
        ),
    ]
