# Generated by Django 5.0 on 2023-12-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_remove_categorie_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='name',
        ),
    ]
