# Generated by Django 5.0 on 2023-12-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_remove_condition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.TextField(),
        ),
    ]
