# Generated by Django 5.0 on 2023-12-17 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_alter_amount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='product',
        ),
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.amount'),
        ),
    ]
