# Generated by Django 5.0 on 2023-12-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_remove_amount_product_alter_price_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
    ]
