# Generated by Django 5.0 on 2023-12-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_remove_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='product',
        ),
    ]
