# Generated by Django 5.0 on 2023-12-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_rename_status_status_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
