# Generated by Django 5.0 on 2023-12-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_alter_buyer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_status',
            old_name='paymment_method',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
