# Generated by Django 5.0 on 2023-12-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0022_rename_paymment_method_transaction_status_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
