# Generated by Django 5.0 on 2023-12-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0024_productimage_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
